version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db # MySQLサービスに依存
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:password@db:3306/myapp_development # MySQL接続情報

  db:
    image: mysql:8.0 # MySQLのイメージ
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password # ルートユーザーのパスワード
      MYSQL_DATABASE: myapp_development # データベース名
    volumes:
      - db_data:/var/lib/mysql # MySQLのデータ永続化用
    ports:
      - "3306:3306" # ホストからMySQLにアクセスしたい場合に開放（開発時便利）

volumes:
  mysql_data:
