version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
      - js_builder
      - css_builder
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:password@db:3306/myapp_development

    command: sh -c "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0"

  js_builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: bash -c "yarn install --immutable && yarn build --watch=forever"

  css_builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: bash -c "yarn install --immutable && yarn build:css --watch"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
  node_modules:
